stages:
  - build
    - deploy

build:
  image: node:16
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    # Do not clone git repo
    GIT_STRATEGY: none
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public
