version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/data:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8083:8080

volumes:
  db:
